### ISSUE TITLE
Remove API dependency

### ISSUE THREAD

**Issue by ridaamirini** [ridaamirini/ImapSyncClient#15]
@utoppo thanks for reporting the GDPR issue 

I will remove the API and use the imapsync binary. 

This will be released in the next major update. (See 1.0 branch)

**Comment by marc-schumann** [comment]
is there a date when version 1.0 is gonna be released as an dmg or something?

**Comment by ridaamirini** [comment]
@marc-schumann I hope this month. It's mostly done but i don't have time to test.
