### ISSUE TITLE
Requires Node.js?

### ISSUE THREAD

**Issue by gitChriss** [ridaamirini/ImapSyncClient#20]
After starting the migration I get the following Error:

Failed to migrate (account1 => account2) [Failed]
Error: Node.js was not found in the default path. Please specify the location.

Now what? Were do I specify the path? Do I just need to install Node.js on my system? (Using MacOS 10.13.6)

**Comment by ridaamirini** [comment]
Yes you need to install Node.js.

The path will be found automatically.

**Comment by gitChriss** [comment]
Unfortunately I already tried that. Installed node.js and even rebooted the system. Same error. :-/

**Comment by ridaamirini** [comment]
Could you please try to execute `which node` or `which nodejs` In your Terminal.

It should output `/usr/local/bin/node`

**Comment by gitChriss** [comment]
Yep:

```
Chriss-iMac:~ chriss$ which node
/usr/local/bin/node

Chriss-iMac:~ chriss$ which nodejs
(No output)
```

**Comment by ridaamirini** [comment]
Ok i will investigate this issue.

**Comment by ridaamirini** [comment]
Its a bug from https://github.com/shelljs/shelljs/issues/704

**Comment by ridaamirini** [comment]
Maybe you have suggestion how we could workaround this issue.
