### ISSUE TITLE
Stopped! click on console to view the LOG

### ISSUE THREAD

**Issue by muhammadfaisal678** [ridaamirini/ImapSyncClient#29]
I've installed and tried this tool on Windows, MAC and Linux but the behavior was same. It always says that "Stopped! click on console to view the LOG" but there's no details or logs so, no idea what's going on. 

any suggestion will be appreciated.

**Comment by ridaamirini** [comment]
It's hard to say without any error. (I know i need to rework the error logging in same edge cases)

But here is an alternative for you https://i005.lamiral.info/X/ 
we are using the same script to sync mailboxes.
